import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocialPlatformProvider } from '@/contexts/SocialPlatformContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="inset-0 bg-gradient-to-r from-purple-300 via-pink-300 to-blue-300 animate-gradient-x "> 
        <SocialPlatformProvider>
        {children}
        </SocialPlatformProvider>
       
        </div>
      </body>
    </html>
  );
}
